In [2]:
import yfinance as yf
ticker = yf.Ticker('GOOGL').info
market_price = ticker['regularMarketPrice']
previous_close_price = ticker['regularMarketPreviousClose']
print('Ticker: GOOGL')
print('Market Price:', market_price)
print('Previous Close Price:', previous_close_price)

KeyError: 'regularMarketPreviousClose'

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from scipy.optimize import curve_fit
from numpy import arange
from pandas import read_csv
import math
import datetime 
from datetime import timedelta
from datetime import date
import calendar
from statistics import mean
import yfinance as yf

In [40]:
start_date = '2023-03-12'
end_date = '2023-03-19'
 
# Set the ticker
ticker = 'MUFG'
#tickers_list = ['^GSPC','AAPL', 'TSLA', 'JPM', 'MSFT', 'AMZN', 'GOOGL',
#'BRK-B','UNH','GOOG','XOM','JNJ','NVDA','PG','V','META','XPEV','PLUG','LXRX']
# Get the data
#data = yf.download(tickers="MSFT", period="5d", interval="1m")
data = yf.download(ticker, start_date, end_date,interval="1m")

[*********************100%***********************]  1 of 1 completed

In [41]:
data

                      Open    High    Low  Close  Adj Close  Volume
Datetime
2023-03-13 09:30:00  6.520  6.5800  6.490  6.510      6.510  230617
2023-03-13 09:31:00  6.505  6.5050  6.450  6.465      6.465   95569
2023-03-13 09:32:00  6.465  6.4800  6.440  6.440      6.440   31610
2023-03-13 09:33:00  6.445  6.4750  6.435  6.470      6.470  108948
2023-03-13 09:34:00  6.470  6.4919  6.470  6.490      6.490   39961
...                    ...     ...    ...    ...        ...     ...
2023-03-17 15:56:00  6.145  6.1475  6.130  6.135      6.135  103821
2023-03-17 15:57:00  6.135  6.1400  6.130  6.130      6.130   25676
2023-03-17 15:58:00  6.130  6.1400  6.130  6.135      6.135   45472
2023-03-17 15:59:00  6.140  6.1500  6.130  6.150      6.150  306621
2023-03-17 16:00:00  6.140  6.1400  6.140  6.140      6.140       0

[1934 rows x 6 columns]

In [42]:
dat=data['Adj Close']

In [43]:
dat

Datetime
2023-03-13 09:30:00    6.510
2023-03-13 09:31:00    6.465
2023-03-13 09:32:00    6.440
2023-03-13 09:33:00    6.470
2023-03-13 09:34:00    6.490
                       ...
2023-03-17 15:56:00    6.135
2023-03-17 15:57:00    6.130
2023-03-17 15:58:00    6.135
2023-03-17 15:59:00    6.150
2023-03-17 16:00:00    6.140
Name: Adj Close, Length: 1934, dtype: float64

In [44]:
dat.to_csv(r'/Users/zlatatabachova/Documents/python/mitsubishi.txt', sep=';')

In [10]:
data.index

DatetimeIndex(['2023-01-03 09:30:00', '2023-01-03 09:31:00',
               '2023-01-03 09:32:00', '2023-01-03 09:33:00',
               '2023-01-03 09:34:00', '2023-01-03 09:35:00',
               '2023-01-03 09:36:00', '2023-01-03 09:37:00',
               '2023-01-03 09:38:00', '2023-01-03 09:39:00',
               ...
               '2023-01-03 15:50:00', '2023-01-03 15:51:00',
               '2023-01-03 15:52:00', '2023-01-03 15:53:00',
               '2023-01-03 15:54:00', '2023-01-03 15:55:00',
               '2023-01-03 15:56:00', '2023-01-03 15:57:00',
               '2023-01-03 15:58:00', '2023-01-03 15:59:00'],
              dtype='datetime64[ns]', name='Datetime', length=390, freq=None)

In [11]:
prices=pd.DataFrame(list(zip(data.index)))

In [12]:
dat=data['Adj Close']

In [13]:
dat

,AAPL,AMZN,BRK-B,GOOG,GOOGL,JNJ,JPM,LXRX,META,MSFT,NVDA,PG,PLUG,TSLA,UNH,V,XOM,XPEV,^GSPC
Datetime,,,,,,,,,,,,,,,,,,,
2023-01-03 09:30:00,129.770004,85.440002,309.899994,90.209999,89.820000,176.580002,134.949997,1.970,123.800003,242.160004,147.619995,151.559998,12.750,117.089996,524.510010,210.373001,109.019997,10.6800,3856.679932
2023-01-03 09:31:00,129.639999,85.486000,309.799988,89.989998,89.570000,176.490005,135.169998,NaN,124.160004,242.080002,147.330002,151.440002,12.700,116.490303,523.505005,210.660004,109.290001,10.6300,3855.199951
2023-01-03 09:32:00,129.460007,85.500000,310.070007,90.370003,89.970001,176.649994,135.225006,NaN,124.830002,242.720093,147.710007,151.539993,12.770,115.790001,523.200012,210.559998,109.279999,10.7100,3856.919922
2023-01-03 09:33:00,130.029602,85.739998,310.628693,90.724998,90.300003,177.089996,135.669998,1.980,125.010002,243.850006,148.399994,151.350006,12.815,116.309898,524.349976,211.227005,109.370003,10.8100,3865.310059
2023-01-03 09:34:00,129.839996,85.769997,310.454987,90.699997,90.279999,176.862000,135.630005,1.980,125.250000,243.246704,147.320007,151.184998,12.720,115.720001,522.832520,211.009995,109.390701,10.8300,3860.620117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-03 15:55:00,125.165001,85.900002,309.890015,89.555000,89.004997,178.229996,135.014999,2.000,124.785004,239.559998,143.119995,151.619995,12.200,108.136497,518.250000,207.309998,106.559998,10.1550,3824.139893
2023-01-03 15:56:00,125.150002,85.894997,309.670013,89.485001,88.953003,178.259995,134.925003,1.990,124.800003,239.485199,142.979996,151.600006,12.180,107.970001,518.030029,207.240005,106.455002,10.1550,3822.590088
2023-01-03 15:57:00,125.214996,85.925003,309.890015,89.620003,89.084999,178.339996,135.005005,1.995,124.792900,239.679993,143.169998,151.675003,12.185,108.021004,518.339417,207.389999,106.540001,10.1900,3825.010010
2023-01-03 15:58:00,125.254997,85.900002,309.839996,89.679604,89.150002,178.350006,134.979996,1.990,124.821098,239.679993,143.178406,151.669998,12.180,108.070999,518.699829,207.460007,106.570000,10.1600,3825.500000
2023-01-03 15:59:00,125.050003,85.820000,309.769989,89.690002,89.129997,178.169998,135.059998,2.000,124.750000,239.539993,143.149994,151.550003,12.170,108.062698,518.330017,207.320007,106.470001,10.1893,3824.070068

In [47]:
prices

                      0
0   2022-11-28 09:30:00
1   2022-11-28 09:31:00
2   2022-11-28 09:32:00
3   2022-11-28 09:33:00
4   2022-11-28 09:34:00
..                  ...
775 2022-11-29 15:55:00
776 2022-11-29 15:56:00
777 2022-11-29 15:57:00
778 2022-11-29 15:58:00
779 2022-11-29 15:59:00

[780 rows x 1 columns]

In [48]:
data['Adj Close']

,AAPL,AMZN,BRK.B,GOOG,GOOGL,JNJ,JPM,LXRX,META,MSFT,NVDA,PG,PLUG,TSLA,UNH,V,XOM,XPEV,^GSPC
2022-11-28 09:30:00,145.229996,94.055000,NaN,96.940002,96.779999,177.110001,136.410004,2.1200,111.160004,245.804993,160.966095,146.490005,15.655,180.137207,538.119995,212.919998,110.309998,6.9300,4000.389893
2022-11-28 09:31:00,145.639999,94.400002,NaN,97.010002,96.805000,177.186493,136.600006,2.1200,111.350098,245.529800,162.080002,146.699997,15.750,181.119995,538.825012,213.115005,109.769897,7.0100,4002.919922
2022-11-28 09:32:00,145.860001,94.459999,NaN,96.809998,96.599998,177.179993,136.600006,NaN,111.653999,245.990005,162.380005,146.710007,15.710,181.110001,538.104980,212.960007,110.035004,7.0050,4005.830078
2022-11-28 09:33:00,146.119995,94.879997,NaN,96.829399,96.629997,176.979996,136.410004,NaN,111.449997,245.785004,162.149994,146.554993,15.790,181.210007,538.000000,212.994995,109.949997,7.0600,4006.870117
2022-11-28 09:34:00,146.089996,94.964996,NaN,97.080002,96.858902,177.029999,136.410004,2.1100,111.940002,245.881393,162.100006,146.550003,15.730,181.750000,537.575012,213.554993,109.849998,7.1450,4008.389893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-29 15:55:00,141.179993,92.448402,NaN,95.360001,95.150002,175.979996,136.464996,2.0550,109.424301,240.389999,156.368698,145.419998,14.895,180.735001,527.835022,208.350006,110.480003,7.3400,3956.770020
2022-11-29 15:56:00,141.285507,92.485001,NaN,95.445000,95.214996,175.985001,136.539993,2.0592,109.440002,240.599899,156.520004,145.500000,14.890,180.940094,528.479980,208.440002,110.500000,7.3300,3958.290039
2022-11-29 15:57:00,141.225006,92.440002,NaN,95.434998,95.220001,176.089996,136.589996,2.0550,109.430000,240.500000,156.490005,145.479996,14.880,180.789993,527.900024,208.380005,110.510002,7.3300,3958.080078
2022-11-29 15:58:00,141.235001,92.434998,NaN,95.449997,95.209999,176.070007,136.559998,2.0600,109.427002,240.475006,156.479996,145.460007,14.870,180.824997,527.989990,208.449997,110.544998,7.3550,3958.090088
2022-11-29 15:59:00,141.160004,92.400002,NaN,95.419998,95.190002,176.089996,136.550003,2.0550,109.459999,240.289993,156.369995,145.440002,14.895,180.820007,527.799988,208.880005,110.529999,7.3578,3957.350098

In [ ]:
;AAPL;AMZN;BRK.B;GOOG;GOOGL;JNJ;JPM;LXRX;META;MSFT;NVDA;PG;PLUG;TSLA;UNH;V;XOM;XPEV;^GSPC

In [49]:
tab = pd.read_csv('/Users/zlatatabachova/Documents/entropy/data/october/missing_october.txt', delimiter=';') 
tab.head

FileNotFoundError: [Errno 2] No such file or directory: '/Users/zlatatabachova/Documents/entropy/data/october/missing_november.txt'

In [5]:
tab.columns=['created_at','Apple Inc.','Amazon.com Inc.','Berkshire Hathaway Inc. Cl B.','Alphabet Inc. Cl C',
'Alphabet Inc. Cl A','Johnson & Johnson','JPMorgan Chase & Co.','Lexicon Pharmaceuticals Inc.',
'Meta Platforms Inc.','Microsoft Corp.','NVIDIA Corp.','Procter & Gamble Co.','Plug Power Inc.',
'Tesla Inc.','UnitedHealth Group Inc.','Visa Inc. Cl A','Exxon Mobil Corp.','XPeng Inc. ADR','S&P 500 Index']

In [6]:
tab.head

<bound method NDFrame.head of                created_at  Apple Inc.  Amazon.com Inc.  \
0     2022-10-21 09:30:00  143.350006       114.760002
1     2022-10-21 09:31:00  143.139999       115.300003
2     2022-10-21 09:32:00  143.365005       115.860001
3     2022-10-21 09:33:00  143.104996       115.589996
4     2022-10-21 09:34:00  142.889999       115.230003
...                   ...         ...              ...
1555  2022-10-26 15:55:00  149.240005       115.690002
1556  2022-10-26 15:56:00  149.264999       115.650002
1557  2022-10-26 15:57:00  149.220001       115.544998
1558  2022-10-26 15:58:00  149.139999       115.470100
1559  2022-10-26 15:59:00  149.509995       115.699997

      Berkshire Hathaway Inc. Cl B.  Alphabet Inc. Cl C  Alphabet Inc. Cl A  \
0                               NaN           98.470001           97.945000
1                               NaN           99.029999           98.519997
2                               NaN           99.360001           98.839996
3                               NaN           99.000000           98.529999
4                               NaN           98.800003           98.360001
...                             ...                 ...                 ...
1555                            NaN           95.084999           95.129997
1556                            NaN           94.974998           95.074997
1557                            NaN           94.838303           94.949997
1558                            NaN           94.834999           94.934998
1559                            NaN           94.849998           94.930000

      Johnson & Johnson  JPMorgan Chase & Co.  Lexicon Pharmaceuticals Inc.  \
0            164.880005            116.750000                        1.9171
1            164.889999            117.209999                        1.9104
2            165.110001            116.869698                        1.9000
3            164.830002            116.570000                        1.9100
4            164.520004            116.550003                        1.8900
...                 ...                   ...                           ...
1555         172.440002            124.050003                        2.1300
1556         172.389999            124.095001                        2.1300
1557         172.399994            124.114998                        2.1250
1558         172.320007            124.029999                        2.1250
1559         172.250000            124.089996                        2.1100

      Meta Platforms Inc.  Microsoft Corp.  NVIDIA Corp.  \
0              126.839996       235.179993    120.650101
1              128.225998       235.710007    121.209999
2              128.820007       236.199997    121.879997
3              128.410004       235.880005    120.930000
4              127.510002       235.625000    120.305000
...                   ...              ...           ...
1555           129.710007       231.779999    129.169296
1556           129.669998       231.679993    129.059998
1557           129.664993       231.417496    128.928604
1558           129.419998       231.179993    128.919998
1559           129.779999       231.240005    128.949997

      Procter & Gamble Co.  Plug Power Inc.  Tesla Inc.  \
0                      NaN        15.985000  205.168594
1               126.599998        15.990000  206.750000
2               127.080002        16.109900  207.399994
3               127.400002        15.940000  206.815002
4               126.989998        15.920000  206.122498
...                    ...              ...         ...
1555            132.029999        16.485001  224.389999
1556            131.919998        16.465000  224.460007
1557            131.921997        16.445000  224.569901
1558            131.899994        16.430000  224.339996
1559            131.800003        16.440001  224.600006

      UnitedHealth Group Inc.  Visa Inc. Cl A  Exxon Mobil Corp.  \
0                  520.020020      185.250000         104.150002
1                  519.530029      186.074997         104.639999
2                  520.609985      186.488800         104.769997
3                  519.265015      186.000000         104.610001
4                  518.669983      185.929993         104.584999
...                       ...             ...                ...
1555               543.284973      203.720001         107.290001
1556               543.369995      203.619995         107.230003
1557               543.299988      203.574997         107.190002
1558               542.909973      203.339996         107.160004
1559               543.309998      203.399994         107.169998

      XPeng Inc. ADR  S&P 500 Index
0             7.6850    3652.840088
1             7.6900    3659.689941
2             7.7400    3665.560059
3             7.7099    3660.110107
4             7.6700    3655.370117
...              ...            ...
1555          8.1850    3834.010010
1556          8.1850    3832.669922
1557          8.1900    3831.070068
1558          8.1900    3829.159912
1559          8.1850    3830.620117

[1560 rows x 20 columns]>

In [9]:
datum=tab['created_at']

In [10]:
datum.head

<bound method NDFrame.head of 0       2022-10-21 09:30:00
1       2022-10-21 09:31:00
2       2022-10-21 09:32:00
3       2022-10-21 09:33:00
4       2022-10-21 09:34:00
               ...
1555    2022-10-26 15:55:00
1556    2022-10-26 15:56:00
1557    2022-10-26 15:57:00
1558    2022-10-26 15:58:00
1559    2022-10-26 15:59:00
Name: created_at, Length: 1560, dtype: object>

In [17]:
tab.query("created_at == '2022-10-21 09:31:00'").index

Int64Index([1], dtype='int64')